import About from './About'
import Hero from './Hero'
import Nav from './nav'
import Footer from './footer'
import Services from './services'
import FAQs from './FAQs'
import Number from './Number'
import Team from './Team'
import Project from './projects'
import Wedo from './we_do'
import ClientSlider from './weareworkingwith'
import Path from './path'
import LoginPage from './Login'
import RegistrationPage from './register'
import PageNotFound from './internship'
import ResetPassword from './resetpassword'
import ContactMe from './contact'
import Internship from './internship'
import Blog from './blog'
import OurClients from './OurClients'
import IndustriesWeServe from './IndustriesWeServe'
    
//MAIN INDEX TO IMPORT RECENTLY CREATED COMPONENTS OR NEW ADDED WEB PAGES

export { About, Hero, Nav, OurClients, IndustriesWeServe,FAQs, Footer, Number, Team, Project, Wedo, Services, ClientSlider, Path, LoginPage, RegistrationPage, PageNotFound, ResetPassword, ContactMe, Internship, Blog } 
